# -*- coding: utf-8 -*-
"""Hw1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVJAfH3LgG49v_TqY-SxVFfHQEEpcbwN
"""

#23.1
import folium
m=folium.Map(location=[10.761097765603395, 106.66834914776304],zoom_start=13)
folium.Marker([10.761097765603395, 106.66834914776304], popup="UEH",tooltip="Click vào", icon=folium.Icon(color='red')).add_to(m)
folium.Marker([10.75796490581001, 106.65954962108378], popup="Bệnh viện Chợ Rẫy", tooltip="Click vào").add_to(m)
folium.Marker([10.771803963801421, 106.66966154911657], popup="Vạn Hạnh Mall", tooltip="Click vào").add_to(m)
folium.Marker([10.761306153121895, 106.67272463181955], popup="Chùa Giác Ngộ", tooltip="Click vào").add_to(m)
folium.Marker([10.761179671241916, 106.6633583581005], popup="Sân vận động Thống Nhất", tooltip="Click vào").add_to(m)
folium.Marker([10.763834469421207, 106.66833015453257], popup="Văn phòng Kinh tế và Văn hóa Đài Bắc", tooltip="Click vào").add_to(m)
m

#23.2
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
import folium
geolocator = Nominatim(user_agent="geoapi", timeout=10)
# Điểm trung tâm ( Dinh Độc Lập )
location = geolocator.geocode("Independence Palace, Ho Chi Minh City")
center_coord=(location.latitude, location.longitude)
print(f"Tên: {location.address}")
print(f"Tọa độ: {location.latitude}, {location.longitude}")
# Danh sách 10 địa chỉ cụ thể
addresses = [
    "Ben Thanh Market, Ho Chi Minh City",
    "Tan Son Nhat Airport, Ho Chi Minh City",
    "Notre Dame Cathedral, Ho Chi Minh City",
    "Bitexco Financial Tower, Ho Chi Minh City",
    "War Remnants Museum, Ho Chi Minh City",
    "Thao Cam Vien, Ho Chi Minh City",
    "Landmark 81, Ho Chi Minh City",
    "Van Hanh Mall, Ho Chi Minh City",
    "Suoi Tien Park, Ho Chi Minh City",
    "Dam Sen Park, Ho Chi Minh City"
]
#Lấy tọa độ từng địa chỉ và tính khoảng cách đến Dinh ĐL
locations=[]
for addr in addresses:
   loc = geolocator.geocode(addr)
   coord=(loc.latitude, loc.longitude)
   dist=geodesic(center_coord, coord).km
   locations.append((addr, coord, dist))
   print(f"Tên: {loc.address}")
   print(f"Tọa độ: {loc.latitude}, {loc.longitude}")
   print(f"Khoảng cách thực tế: {dist:.2f} km")
m = folium.Map(location=center_coord, zoom_start=13)
folium.Marker(center_coord, popup="Dinh Doc Lap",tooltip="Click vào", icon=folium.Icon(color='red')).add_to(m)
for name, coords, dist in locations:
    folium.Marker(coords, popup=f"{name}\n{dist:.2f} km").add_to(m)
    folium.PolyLine([coords, center_coord], color="gray").add_to(m)
m

#23.3
import folium
from folium.plugins import HeatMap
m = folium.Map(location=[10.775, 106.700], zoom_start=13)
heat_data= [
   # Khu vực Quận 1 - Trung tâm (mật độ cao)
    [10.7769, 106.7008],
    [10.7750, 106.7020],
    [10.7785, 106.6990],
    [10.7800, 106.6980],
    [10.7775, 106.7015],
    [10.7745, 106.6995],
    [10.7790, 106.7000],
    # Khu vực Quận 3 (mật độ cao)
    [10.7820, 106.6950],
    [10.7835, 106.6930],
    [10.7810, 106.6960],
    [10.7840, 106.6940],
    # Khu vực Quận 5 (mật độ trung bình)
    [10.7560, 106.6650],
    [10.7580, 106.6680],
    [10.7555, 106.6660],
    # Khu vực Quận 10 (mật độ trung bình)
    [10.7620, 106.6750],
    [10.7680, 106.6800],
    [10.7650, 106.6780],
    # Khu vực Quận 7 (mật độ trung bình - khá)
    [10.7300, 106.7100],
    [10.7350, 106.7150],
    [10.7320, 106.7120],
    [10.7380, 106.7180],
    # Khu vực Thủ Đức (mật độ thấp)
    [10.8000, 106.7200],
    [10.8100, 106.7250],
    [10.8050, 106.7220],
    # Khu vực Tân Bình (mật độ trung bình)
    [10.7900, 106.6500],
    [10.7950, 106.6400],
]
HeatMap(heat_data).add_to(m)
folium.Marker([10.7769, 106.7008],  popup="Vùng mật độ cao - Khu vực trung tâm Quận 1, 3", icon=folium.Icon(color='red')).add_to(m)
folium.Marker([10.7300, 106.7100], popup="Vùng mật độ trung bình - Quận 7", icon=folium.Icon(color='orange')).add_to(m)
folium.Marker([10.8000, 106.7200], popup="Vùng mật độ thấp - Thủ Đức", icon=folium.Icon(color='green')).add_to(m)
m

#23.5
import folium
warehouse = [10.775, 106.700]
m = folium.Map(location=warehouse, zoom_start=13)
# Vẽ vòng tròn bán kính 3 km (màu xanh dương)
folium.Circle(location=warehouse,radius=3000,color='blue',fill=True, popup='3 km').add_to(m)
# Vẽ vòng tròn bán kính 5 km (màu xanh lá)
folium.Circle(location=warehouse,radius=5000,color='green',fill=True,popup='5 km').add_to(m)
# Vẽ vòng tròn bán kính 10 km (màu cam)
folium.Circle(location=warehouse,radius=10000,color='orange',fill=True,popup='10 km').add_to(m)
# Thêm marker cho trung tâm phân phối
folium.Marker(location=warehouse,popup='Trung tâm phân phối',icon=folium.Icon(color='red')).add_to(m)
m

#23.6
import osmnx as ox
import folium
import geopandas as gpd
# Cấu hình cache
ox.settings.use_cache = True
# 1. Tải mạng lưới đường bộ của Quận 1
place = "District 1, Ho Chi Minh City, Vietnam"
G = ox.graph_from_place(place, network_type='drive')
# 2. Phân tích cơ bản
n_nodes = G.number_of_nodes()
n_edges = G.number_of_edges()
print(f"Số nút giao: {n_nodes}")
print(f"Số đoạn đường: {n_edges}")
# Tổng chiều dài (mét -> km)
total_length_m = sum(data['length'] for u, v, data in G.edges(data=True))
total_length_km = total_length_m / 1000
print(f"Tổng chiều dài đường: {total_length_km:.2f} km")
# Chiều dài trung bình mỗi đoạn
avg_length_m = total_length_m / n_edges
print(f"Chiều dài trung bình mỗi đoạn: {avg_length_m:.2f} mét")
# 3. Tính diện tích khu vực
gdf_place = ox.geocode_to_gdf(place)
# Chuyển sang hệ tọa độ mét
gdf_place_proj = gdf_place.to_crs(gdf_place.estimate_utm_crs())
area_m2 = gdf_place_proj.geometry.area.iloc[0]
area_km2 = area_m2 / 1_000_000
print(f"Diện tích khu vực: {area_km2:.2f} km²")
# Mật độ mạng lưới (km đường / km²)
density = total_length_km / area_km2
print(f"Mật độ mạng lưới: {density:.2f} km/km²")
# 4. Trực quan hóa bằng Folium
# Lấy tọa độ trung tâm từ ranh giới
projected_centroid_point = gdf_place_proj.geometry.centroid.iloc[0]
# Convert the shapely Point to a geopandas GeoSeries to apply to_crs
geographic_centroid_gs = gpd.GeoSeries([projected_centroid_point], crs=gdf_place_proj.crs).to_crs(gdf_place.crs)
geographic_centroid = geographic_centroid_gs.iloc[0]
center_lat = geographic_centroid.y
center_lon = geographic_centroid.x
m = folium.Map(location=[center_lat, center_lon], zoom_start=13)
# Vẽ từng edge
for u, v, data in G.edges(data=True):
    x1, y1 = G.nodes[u]['x'], G.nodes[u]['y']
    x2, y2 = G.nodes[v]['x'], G.nodes[v]['y']
    folium.PolyLine([(y1, x1), (y2, x2)], color='blue', weight=2, opacity=0.6).add_to(m)
folium.GeoJson(gdf_place.geometry.iloc[0]).add_to(m)
m

!pip install folium geopy osmnx networkx

#23.7
import osmnx as ox
import networkx as nx
import folium
from geopy.distance import geodesic
ox.settings.use_cache = True
# Tải mạng đường Quận 1
G = ox.graph_from_place("District 1, Ho Chi Minh City, Vietnam", network_type='drive')
# Tọa độ 2 điểm (Chợ Bến Thành, Dinh Độc Lập)
start = (10.7758, 106.7009)
end = (10.7769, 106.6952)
# Tìm nút gần nhất
orig = ox.distance.nearest_nodes(G, start[1], start[0])
dest = ox.distance.nearest_nodes(G, end[1], end[0])
# Heuristic cho A*
def h(u, v):
    u_coord = (G.nodes[u]['y'], G.nodes[u]['x'])
    v_coord = (G.nodes[v]['y'], G.nodes[v]['x'])
    return geodesic(u_coord, v_coord).km
# Dijkstra
path_d = nx.shortest_path(G, orig, dest, weight='length')
len_d = nx.shortest_path_length(G, orig, dest, weight='length') / 1000
# A*
path_a = nx.astar_path(G, orig, dest, heuristic=h, weight='length')
len_a = sum(G[u][v][0]['length'] for u, v in zip(path_a[:-1], path_a[1:])) / 1000
print(f"Dijkstra: {len_d:.2f} km, A*: {len_a:.2f} km")
# Vẽ bản đồ
coords_d = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in path_d]
coords_a = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in path_a]
m = folium.Map()
folium.PolyLine(coords_d, color='blue', weight=5).add_to(m)
folium.PolyLine(coords_a, color='red', weight=3).add_to(m)
folium.Marker(start, popup='Chợ Bến Thành').add_to(m)
folium.Marker(end, popup='Dinh Độc Lập').add_to(m)
all_points = coords_d + coords_a
m.fit_bounds([min(all_points), max(all_points)])
m

#23.8
# HỆ THỐNG GÁN XE GẦN NHẤT CHO KHÁCH HÀNG
import folium
import random
from geopy.distance import geodesic
# 1. Tọa độ trung tâm khu vực (Chợ Bến Thành)
center = (10.7758, 106.7009)
# 2. Tạo danh sách xe (ID, tọa độ)
vehicles = {
    "Xe A": (10.7700, 106.7050),
    "Xe B": (10.7800, 106.6950),
    "Xe C": (10.7850, 106.7100),
}
# 3. Tạo danh sách khách hàng
customers = {
    "Khách 1": (10.7720, 106.6980),
    "Khách 2": (10.7780, 106.7020),
    "Khách 3": (10.7820, 106.7080),
    "Khách 4": (10.7680, 106.6930),
    "Khách 5": (10.7900, 106.7150),
}
# 4. Hàm tính khoảng cách (km)
def distance(coord1, coord2):
    return geodesic(coord1, coord2).km
# 5. Ghép cặp: mỗi khách gán cho xe gần nhất
assignments = {}
for cust_name, cust_coord in customers.items():
    nearest_vehicle = None
    min_dist = float('inf')
    for veh_name, veh_coord in vehicles.items():
        d = distance(cust_coord, veh_coord)
        if d < min_dist:
            min_dist = d
            nearest_vehicle = veh_name
    assignments[cust_name] = (nearest_vehicle, min_dist)
# 6. In kết quả ghép cặp
print("=== KẾT QUẢ GHÉP XE ===")
for cust, (veh, dist) in assignments.items():
    print(f"{cust} -> {veh} (khoảng cách {dist:.2f} km)")
# 7. Vẽ bản đồ Folium
m = folium.Map(location=center, zoom_start=13)
# Vẽ các xe (màu xanh)
for veh_name, coord in vehicles.items():
    folium.Marker(
        coord,
        popup=f" {veh_name}",
        icon=folium.Icon(color='blue', icon='car', prefix='fa')
    ).add_to(m)
# Vẽ các khách (màu đỏ)
for cust_name, coord in customers.items():
    folium.Marker(
        coord,
        popup=f"{cust_name}",
        icon=folium.Icon(color='red', icon='user', prefix='fa')
    ).add_to(m)
# Vẽ đường nối từ mỗi khách đến xe được gán
for cust_name, (veh_name, dist) in assignments.items():
    cust_coord = customers[cust_name]
    veh_coord = vehicles[veh_name]
    folium.PolyLine(
        [cust_coord, veh_coord],
        color='green',
        weight=2,
        opacity=0.6,
        popup=f"{cust_name} → {veh_name} ({dist:.2f} km)"
    ).add_to(m)

all_points = list(vehicles.values()) + list(customers.values())
m.fit_bounds([min(all_points), max(all_points)])
m

#23.9
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import folium
# 1. TẠO vị trí khách hàng
np.random.seed(42)
num_customers = 200
lats = np.random.uniform(10.7, 10.9, num_customers)
lons = np.random.uniform(106.6, 106.8, num_customers)
df_customers = pd.DataFrame({
    'CustomerID': range(1, num_customers + 1),
    'Lat': lats,
    'Lon': lons
})
# 2. K-MEANS (K=3)
k = 3
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
df_customers['Cluster'] = kmeans.fit_predict(df_customers[['Lat', 'Lon']])
centroids = kmeans.cluster_centers_
df_warehouses = pd.DataFrame(centroids, columns=['Lat', 'Lon'])
df_warehouses['WarehouseID'] = range(1, k + 1)
# 3. VẼ BẢN ĐỒ FOLIUM
map_center = [df_customers['Lat'].mean(), df_customers['Lon'].mean()]
m = folium.Map(location=map_center, zoom_start=12)
# Màu sắc cho các cụm khách hàng
colors = ['#3498db', '#e74c3c', '#2ecc71']
# Vẽ khách hàng
for _, row in df_customers.iterrows():
    cluster_id = int(row['Cluster'])
    folium.CircleMarker(
        location=[row['Lat'], row['Lon']],
        radius=4,
        color=colors[cluster_id],
        fill=True,
        fill_color=colors[cluster_id],
        fill_opacity=0.7,
        popup=f"Khách hàng - Tuyến {cluster_id + 1}"
    ).add_to(m)
# Vẽ kho hàng
warehouse_colors = ['blue', 'red', 'green']
for idx, row in df_warehouses.iterrows():
    folium.Marker(
        location=[row['Lat'], row['Lon']],
        icon=folium.Icon(color=warehouse_colors[idx], icon='home', prefix='fa'),
        popup=f"KHO TRUNG CHUYỂN",
        tooltip="Click vào"
    ).add_to(m)
# Hiển thị bản đồ
m

!pip install polyline

#23.10
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import folium
from folium.plugins import HeatMap
np.random.seed(42)
n_roads = 100
data = {
    'lat': np.random.uniform(10.75, 10.82, n_roads),
    'lon': np.random.uniform(106.63, 106.72, n_roads),
    'traffic_volume': np.random.randint(100, 1000, n_roads),
    'avg_speed': np.random.randint(5, 50, n_roads),
    'road_width': np.random.randint(1, 4, n_roads),
    'is_rush_hour': np.random.choice([0, 1], n_roads)
}
df = pd.DataFrame(data)
df['target_risk'] = (df['traffic_volume'] / 1000) * 0.4 + (1 - df['avg_speed'] / 50) * 0.4 + df['is_rush_hour'] * 0.2
X = df[['traffic_volume', 'avg_speed', 'road_width', 'is_rush_hour']]
y = df['target_risk']
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X, y)
df['predicted_risk'] = model.predict(X)
#  TRỰC QUAN HÓA BẢN ĐỒ
m = folium.Map(location=[10.7769, 106.7009], zoom_start=13)
# Thêm HeatMap
heat_data = [[row['lat'], row['lon'], row['predicted_risk']] for index, row in df.iterrows()]
HeatMap(heat_data, radius=25, blur=15, min_opacity=0.5).add_to(m)
# ĐỀ XUẤT TUYẾN ĐƯỜNG THAY THẾ
safe_points = df[df['predicted_risk'] < 0.3].head(5)
route_coords = [[row['lat'], row['lon']] for index, row in safe_points.iterrows()]
if len(route_coords) > 1:
    folium.PolyLine(route_coords, color="green", weight=5, opacity=0.8,tooltip="Tuyến đường thay thế gợi ý (Rủi ro thấp)").add_to(m)
# Chú thích các điểm nóng
for index, row in df[df['predicted_risk'] > 0.7].head(10).iterrows():
    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=6, color='red', fill=True,
        popup=f"Nguy cơ cao: {row['predicted_risk']:.2f}"
    ).add_to(m)
m

#23.11
import numpy as np
import pandas as pd
import folium
from sklearn.ensemble import RandomForestRegressor
# 1. Dữ liệu giả lập
np.random.seed(42)
n = 300
lat = np.random.uniform(10.7, 10.9, n)
lon = np.random.uniform(106.6, 106.8, n)
hour = np.random.randint(0, 24, n)
# Nhu cầu cao ở gần trung tâm (10.78,106.70) và giờ cao điểm (7-9, 17-19)
center_lat, center_lon = 10.78, 106.70
dist = np.sqrt((lat - center_lat)**2 + (lon - center_lon)**2)
demand = 50 * (1 - dist/0.2) + np.random.normal(0, 5, n)
peak = ((hour >= 7) & (hour <= 9)) | ((hour >= 17) & (hour <= 19))
demand[peak] += 30
demand = np.clip(demand, 0, 100)
df = pd.DataFrame({'lat': lat, 'lon': lon, 'hour': hour, 'demand': demand})
# 2. Mô hình Random Forest
X = df[['lat', 'lon', 'hour']]
y = df['demand']
model = RandomForestRegressor(n_estimators=30, random_state=42)
model.fit(X, y)
df['pred_demand'] = model.predict(X)
# 3. Phân tích nhu cầu theo khu vực
df['region'] = 'Khác'
df.loc[(lat > 10.8) & (lon < 106.7), 'region'] = 'Tây Bắc'
df.loc[(lat > 10.8) & (lon >= 106.7), 'region'] = 'Đông Bắc'
df.loc[(lat <= 10.8) & (lon < 106.7), 'region'] = 'Tây Nam'
df.loc[(lat <= 10.8) & (lon >= 106.7), 'region'] = 'Đông Nam'
region_demand = df.groupby('region')['pred_demand'].mean().sort_values(ascending=False)
print("\n=== NHU CẦU TRUNG BÌNH THEO KHU VỰC ===")
for reg, d in region_demand.items():
    print(f"{reg}: {d:.1f}")

m = folium.Map(location=[df['lat'].mean(), df['lon'].mean()], zoom_start=12)
# Màu sắc theo nhu cầu
def color(val):
    return 'green' if val < 30 else 'orange' if val < 60 else 'red'
# Vẽ các điểm khách hàng
for _, row in df.iterrows():
    folium.CircleMarker(
        location=(row['lat'], row['lon']),
        radius=5,
        color=color(row['pred_demand']),
        fill=True,
        fill_opacity=0.7,
        popup=f"Nhu cầu: {row['pred_demand']:.0f} (giờ {int(row['hour'])})"
    ).add_to(m)
# Chú thích
legend_html = '''
<div style="position: fixed; bottom: 20px; right: 20px; background-color: white; padding: 8px; border-radius: 5px; font-size: 12px; z-index: 1000; box-shadow: 2px 2px 5px gray;">
<b>📊 NHU CẦU DỊCH VỤ</b><br>
🟢 Xanh: <30 (thấp)<br>
🟠 Cam: 30–60 (trung bình)<br>
🔴 Đỏ: >60 (cao)
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))
# Kết luận điều phối
print("\n=== ĐỀ XUẤT ĐIỀU PHỐI NGUỒN LỰC ===")
print("- Khu vực Đông Nam và Đông Bắc có nhu cầu cao nhất → cần nhiều xe.")
print("- Giờ cao điểm (7-9h sáng, 17-19h chiều) nhu cầu tăng ~30% → tăng cường xe.")
print("- Có thể điều xe từ vùng Tây Bắc (nhu cầu thấp) sang vùng Đông Nam.")
m

#23.12
import folium
import numpy as np
import random
from geopy.distance import geodesic
# 1. Dữ liệu
warehouses = {
    'Kho 1 (Trung tâm)': (10.7758, 106.7009),
    'Kho 2 (Tây Bắc)':   (10.7850, 106.6850),
    'Kho 3 (Đông Nam)':  (10.7700, 106.7100)
}
np.random.seed(42)
delivery_points = {}
for i in range(1, 31):
    lat = np.random.uniform(10.760, 10.790)
    lon = np.random.uniform(106.685, 106.715)
    delivery_points[f'Điểm {i}'] = (lat, lon)
def dist(p1, p2):
    return geodesic(p1, p2).km
def nearest_neighbor_route(start, points):
    unvisited = points[:]
    route = [start]
    current = start
    while unvisited:
        nearest = min(unvisited, key=lambda p: dist(current, p))
        route.append(nearest)
        current = nearest
        unvisited.remove(nearest)
    return route
# Phương án tối ưu
assign_opt = {}
for name, coord in delivery_points.items():
    d = {wh: dist(coord, wh_coord) for wh, wh_coord in warehouses.items()}
    assign_opt[name] = min(d, key=d.get)
routes_opt = {}
for wh_name, wh_coord in warehouses.items():
    points_of_wh = [delivery_points[p] for p in assign_opt if assign_opt[p] == wh_name]
    if points_of_wh:
        routes_opt[wh_name] = nearest_neighbor_route(wh_coord, points_of_wh)
    else:
        routes_opt[wh_name] = [wh_coord]
total_opt = 0
for route in routes_opt.values():
    for i in range(len(route)-1):
        total_opt += dist(route[i], route[i+1])
# Phương án ngẫu nhiên
random.seed(123)
assign_rand = {name: random.choice(list(warehouses.keys())) for name in delivery_points}
routes_rand = {}
for wh_name, wh_coord in warehouses.items():
    points_of_wh = [delivery_points[p] for p in assign_rand if assign_rand[p] == wh_name]
    if points_of_wh:
        routes_rand[wh_name] = nearest_neighbor_route(wh_coord, points_of_wh)
    else:
        routes_rand[wh_name] = [wh_coord]
total_rand = 0
for route in routes_rand.values():
    for i in range(len(route)-1):
        total_rand += dist(route[i], route[i+1])
# Vẽ bản đồ
m = folium.Map(location=[10.777, 106.700], zoom_start=14)
# Vẽ kho (màu đen)
for name, coord in warehouses.items():
    folium.Marker(coord, popup=name, icon=folium.Icon(color='black', icon='home', prefix='fa')).add_to(m)
# Vẽ điểm giao hàng (màu xám)
for name, coord in delivery_points.items():
    folium.CircleMarker(coord, radius=3, color='gray', fill=True, popup=name).add_to(m)
# Vẽ tuyến tối ưu (xanh dương)
for wh_name, route in routes_opt.items():
    folium.PolyLine(route, color='blue', weight=3, opacity=0.7, popup=f'{wh_name} (tối ưu)').add_to(m)
# Vẽ tuyến ngẫu nhiên (đỏ, nét đứt)
for wh_name, route in routes_rand.items():
    folium.PolyLine(route, color='red', weight=2, opacity=0.5, dash_array='5,5', popup=f'{wh_name} (ngẫu nhiên)').add_to(m)
# Thêm chú thích bằng HTML (cố định vị trí)
legend_html = '''
<div style="position: fixed; bottom: 30px; right: 30px; background-color: white; padding: 8px 12px; border-radius: 6px; font-size: 13px; font-family: Arial; z-index: 1000; box-shadow: 2px 2px 5px rgba(0,0,0,0.3); border: 1px solid gray;">
<b>📌 CHÚ THÍCH</b><br>
⚫ <span style="color:black">Kho hàng</span><br>
🔵 <span style="color:blue">Tuyến tối ưu (gán gần nhất + NN)</span><br>
🔴 <span style="color:red">Tuyến ngẫu nhiên (nét đứt)</span><br>
⚪ <span style="color:gray">Điểm giao hàng</span>
</div>
'''
m.get_root().html.add_child(folium.Element(legend_html))
# In đánh giá
print("="*60)
print("ĐÁNH GIÁ HIỆU QUẢ (3 kho, 30 điểm)")
print("="*60)
print(f"Tổng quãng đường tối ưu: {total_opt:.2f} km")
print(f"Tổng quãng đường ngẫu nhiên: {total_rand:.2f} km")
print(f"Tiết kiệm: {(total_rand - total_opt)/total_rand*100:.1f}%")
for wh_name, route in routes_opt.items():
    length = sum(dist(route[i], route[i+1]) for i in range(len(route)-1))
    print(f"  {wh_name}: {len(route)-1} điểm, {length:.2f} km")
m

#23.13
import folium
from folium import plugins
import numpy as np
import pandas as pd
from geopy.distance import geodesic
# Dữ liệu
warehouses = {
    'Kho Trung tâm': (10.7758, 106.7009),
    'Kho Phía Bắc':   (10.7900, 106.6950),
    'Kho Phía Nam':   (10.7650, 106.7080)
}
np.random.seed(42)
customers = {}
for i in range(1, 41):
    lat = np.random.uniform(10.758, 10.800)
    lon = np.random.uniform(106.688, 106.718)
    customers[f'KH{i}'] = (lat, lon)
def dist(p1, p2):
    return geodesic(p1, p2).km
assign = {}
for c, coord in customers.items():
    d = {wh: dist(coord, wh_coord) for wh, wh_coord in warehouses.items()}
    assign[c] = min(d, key=d.get)
def nearest_route(start, points):
    unvisited = points[:]
    route = [start]
    cur = start
    while unvisited:
        nxt = min(unvisited, key=lambda p: dist(cur, p))
        route.append(nxt)
        cur = nxt
        unvisited.remove(nxt)
    return route
routes = {}
route_lengths = {}
for wh_name, wh_coord in warehouses.items():
    pts = [customers[c] for c in assign if assign[c] == wh_name]
    if pts:
        route = nearest_route(wh_coord, pts)
        routes[wh_name] = route
        total = sum(dist(route[i], route[i+1]) for i in range(len(route)-1))
        route_lengths[wh_name] = total
    else:
        routes[wh_name] = [wh_coord]
        route_lengths[wh_name] = 0
df_stats = pd.DataFrame([
    {'Kho': wh, 'Số khách': sum(1 for c in assign if assign[c]==wh),
     'Quãng đường (km)': round(route_lengths[wh], 2)}
    for wh in warehouses
])
total_customers = len(customers)
total_distance = sum(route_lengths.values())
# Bản đồ
m = folium.Map(location=[10.777, 106.702], zoom_start=14)
# Các lớp
fg_wh = folium.FeatureGroup('🏭 Kho hàng', show=True)
for name, coord in warehouses.items():
    folium.Marker(coord, popup=name, icon=folium.Icon(color='black', icon='home', prefix='fa')).add_to(fg_wh)
fg_cus = folium.FeatureGroup('📦 Khách hàng', show=True)
for name, coord in customers.items():
    folium.CircleMarker(coord, radius=5, color='gray', fill=True,
                        popup=f'{name}<br>Kho: {assign[name]}').add_to(fg_cus)
fg_zone = folium.FeatureGroup('📍 Vùng phục vụ 500m', show=True)
zone_colors = ['blue', 'green', 'orange']
for i, (name, coord) in enumerate(warehouses.items()):
    folium.Circle(coord, radius=500, color=zone_colors[i], fill=True, fill_opacity=0.1).add_to(fg_zone)
fg_route = folium.FeatureGroup('🚚 Tuyến giao hàng', show=True)
route_colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
for i, (name, route) in enumerate(routes.items()):
    folium.PolyLine(route, color=route_colors[i], weight=4, opacity=0.8,
                    popup=f'{name}<br>Dài {route_lengths[name]:.2f} km').add_to(fg_route)
fg_wh.add_to(m); fg_cus.add_to(m); fg_zone.add_to(m); fg_route.add_to(m)
# LayerControl (góc dưới phải)
folium.LayerControl(collapsed=False, position='bottomright').add_to(m)
plugins.Fullscreen().add_to(m)
plugins.MeasureControl(position='topleft', primary_length_unit='kilometers').add_to(m)
# Bảng KPI (góc trên phải)
kpi_html = f'''
<div style="position: fixed; top: 10px; right: 10px; width: 270px; background: white; padding: 8px; border-radius: 8px; z-index: 1000; box-shadow: 0 0 10px gray; font-size: 12px;">
<b>📊 CHỈ SỐ QUẢN TRỊ</b><hr style="margin:4px 0">
👥 Tổng khách: {total_customers}<br>
📏 Tổng quãng đường: {total_distance:.2f} km<br>
📦 Phân bố theo kho:<br>
&nbsp;&nbsp;• {df_stats.iloc[0]['Kho']}: {df_stats.iloc[0]['Số khách']} khách ({df_stats.iloc[0]['Quãng đường (km)']} km)<br>
&nbsp;&nbsp;• {df_stats.iloc[1]['Kho']}: {df_stats.iloc[1]['Số khách']} khách ({df_stats.iloc[1]['Quãng đường (km)']} km)<br>
&nbsp;&nbsp;• {df_stats.iloc[2]['Kho']}: {df_stats.iloc[2]['Số khách']} khách ({df_stats.iloc[2]['Quãng đường (km)']} km)<br>
<hr style="margin:4px 0">
</div>
'''
m.get_root().html.add_child(folium.Element(kpi_html))
m

#23.14
import folium
import numpy as np
import time
from IPython.display import clear_output, display
from geopy.distance import geodesic
# 1. XÂY DỰNG MẠNG LƯỚI ĐƯỜNG ĐƠN GIẢN (DẠNG LƯỚI Ô VUÔNG)
# Tạo các nút giao
lat_min, lat_max = 10.765, 10.790
lon_min, lon_max = 106.690, 106.715
num_nodes = 5
lats = np.linspace(lat_min, lat_max, num_nodes)
lons = np.linspace(lon_min, lon_max, num_nodes)
nodes = {}
idx = 0
for i, lat in enumerate(lats):
    for j, lon in enumerate(lons):
        nodes[(i, j)] = (lat, lon)
        idx += 1
# Kết nối các nút lân cận tạo thành mạng lưới đường
edges = []
for i in range(num_nodes):
    for j in range(num_nodes):
        if i < num_nodes-1:
            edges.append(((i, j), (i+1, j)))
        if j < num_nodes-1:
            edges.append(((i, j), (i, j+1)))
# 2. TẠO CÁC XE VÀ HÀNH TRÌNH
class Vehicle:
    def __init__(self, id, start_node, dest_node, color):
        self.id = id
        self.start = start_node
        self.dest = dest_node
        self.color = color
        self.current = start_node
        self.path = self.find_path(start_node, dest_node)
        self.step = 0
    def find_path(self, start, dest):
        # Tìm đường đi ngắn nhất
        from collections import deque
        queue = deque([(start, [start])])
        visited = set([start])
        while queue:
            node, path = queue.popleft()
            if node == dest:
                return path
            # tìm các nút lân cận
            for (a,b) in edges:
                if a == node and b not in visited:
                    visited.add(b)
                    queue.append((b, path+[b]))
                elif b == node and a not in visited:
                    visited.add(a)
                    queue.append((a, path+[a]))
        return [start]
    def move(self):
        if self.step < len(self.path)-1:
            self.step += 1
            self.current = self.path[self.step]
            return True
        return False
    def get_position(self):
        return nodes[self.current]
    def is_arrived(self):
        return self.step >= len(self.path)-1
# Khởi tạo xe:
vehicles = [
    Vehicle(1, (0,0), (4,4), 'red'),
    Vehicle(2, (0,4), (4,0), 'blue'),
    Vehicle(3, (2,0), (2,4), 'green')
]
# 3. HÀM VẼ BẢN ĐỒ TẠI MỘT THỜI ĐIỂM
def draw_map(step_count, vehicles):
    # Tạo bản đồ trung tâm
    center = ((lat_min+lat_max)/2, (lon_min+lon_max)/2)
    m = folium.Map(location=center, zoom_start=14)
    # Vẽ các nút giao (điểm màu xám)
    for node, coord in nodes.items():
        folium.CircleMarker(coord, radius=3, color='gray', fill=True, popup=str(node)).add_to(m)
    # Vẽ các cạnh (đường phố)
    for (a,b) in edges:
        coord_a = nodes[a]
        coord_b = nodes[b]
        folium.PolyLine([coord_a, coord_b], color='gray', weight=2, opacity=0.5).add_to(m)
    # Vẽ các xe (marker lớn hơn, màu sắc riêng)
    for v in vehicles:
        pos = v.get_position()
        folium.Marker(
            pos,
            popup=f"Xe {v.id} (đến {v.dest})",
            icon=folium.Icon(color=v.color, icon='car', prefix='fa')
        ).add_to(m)
    # Thêm tiêu đề bước thời gian
    title = f'<div style="position: fixed; top: 10px; left: 50px; background: white; padding: 5px; border-radius: 5px;">Bước thời gian: {step_count}</div>'
    m.get_root().html.add_child(folium.Element(title))
    # Chú thích
    legend = '''
    <div style="position: fixed; bottom: 20px; right: 20px; background: white; padding: 5px; font-size: 12px; border-radius: 5px;">
    🚗 Xe đỏ, xanh, lục đang di chuyển theo đường kẻ xám
    </div>
    '''
    m.get_root().html.add_child(folium.Element(legend))
    return m
# 4. CHẠY MÔ PHỎNG THEO BƯỚC THỜI GIAN
print("BẮT ĐẦU MÔ PHỎNG...")
step = 0
max_steps = 15
all_arrived = False
while not all_arrived and step < max_steps:
    # Xóa output cũ và vẽ bản đồ mới
    clear_output(wait=True)
    m = draw_map(step, vehicles)
    display(m)
    # Di chuyển từng xe
    arrived_count = 0
    for v in vehicles:
        if not v.is_arrived():
            v.move()
        if v.is_arrived():
            arrived_count += 1
    if arrived_count == len(vehicles):
        all_arrived = True
        print("Tất cả xe đã đến đích!")
    step += 1
    time.sleep(1.5)
print("Mô phỏng kết thúc.")

#23.15
# Bài toán: Bố trí 4 trạm xe cứu thương ở Hóc Môn sao cho khoảng cách đến các điểm cấp cứu là nhỏ nhất, dựa trên 50 cuộc gọi gần đây.
import numpy as np
import pandas as pd
import folium
from sklearn.cluster import KMeans
from geopy.distance import geodesic
# 1. Dữ liệu 50 cuộc gọi tại Hóc Môn
np.random.seed(42)
center = (10.879, 106.589)
calls = []
for _ in range(50):
    lat = center[0] + np.random.normal(0, 0.025)
    lon = center[1] + np.random.normal(0, 0.025)
    calls.append([lat, lon])
df = pd.DataFrame(calls, columns=['lat', 'lon'])
# 2. Phân cụm 4 trạm
k = 4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(df[['lat', 'lon']])
centroids = kmeans.cluster_centers_
# 3. Thống kê nhanh
print("=== 4 TRẠM XE CỨU THƯƠNG TẠI HÓC MÔN ===")
print(f"Tổng cuộc gọi: {len(df)}")
for i in range(k):
    print(f"Trạm {i+1}: {(df['cluster']==i).sum()} cuộc gọi")
# 4. Đánh giá
df['dist_km'] = df.apply(lambda r: min(geodesic((r.lat,r.lon), (c[0],c[1])).km for c in centroids), axis=1)
print(f"Khoảng cách TB: {df['dist_km'].mean():.2f} km")
print(f"Tỷ lệ trong 1km: {(df['dist_km']<=1).mean()*100:.1f}%")
# 5. Bản đồ với màu sắc theo cụm
m = folium.Map(location=center, zoom_start=12)
colors = ['red', 'blue', 'green', 'orange']
# Vẽ cuộc gọi
for _, r in df.iterrows():
    folium.CircleMarker(
        (r.lat, r.lon),
        radius=3,
        color=colors[int(r['cluster'])],
        fill=True,
        fill_opacity=0.6,
        popup=f"Trạm {int(r['cluster'])+1}"
    ).add_to(m)
# Vẽ trạm
for i, (lat, lon) in enumerate(centroids):
    folium.Marker(
        (lat, lon),
        popup=f"TRẠM {i+1}",
        icon=folium.Icon(color='black', icon='medkit', prefix='fa')
    ).add_to(m)
    folium.Circle((lat, lon), radius=1000, color=colors[i], fill=True, fill_opacity=0.1).add_to(m)
m